

[serve]
deps=["mandelbrot"]
exec="node server.js"

[clean-serve]
deps=["mandelbrot", "clean"]
exec="node server.js"

[clean]
exec="rm -f public/cache/mandelbrot_*.png public/cache/video_*.*"

[display]
deps=["%.png"]
exec="display $<"

["mandelbrot.png"]
deps=["mandelbrot"]
exec="time ./$<"

[check]
deps=["mandelbrot_debug"]
exec="valgrind ./$< -W 140 -H 90 -i 10"

[mandelbrot]
deps=["main.cc", "fixedpt.cc", "lodepng.cpp", "fixedpt.h", "lodepng.h"]
exec="g++ -DNDEBUG -O3 -Wall main.cc fixedpt.cc lodepng.cpp -pthread -o $@"

[mandelbrot_debug]
deps=["main.cc", "fixedpt.cc", "lodepng.cpp", "fixedpt.h", "lodepng.h"]
exec="g++ -g -Wall main.cc fixedpt.cc lodepng.cpp -pthread -o $@"

["fixedpt_%_test"]
deps=["fixedpt_%_test.cc", "fixedpt.cc", "fixedpt.h"]
exec="g++ -g -Wall fixedpt_%_test.cc fixedpt.cc /usr/lib/libgtest_main.a /usr/lib/libgtest.a  -pthread -o $@"

["test_%"]
deps=["fixedpt_%_test"]
exec="./$<"

[test]
deps=["test_62", "test_8", "test_1"]
